ProjectId:
  name: project_id
  in: path
  required: true
  description: Project UUID
  schema:
    type: string
    format: uuid
    example: "123e4567-e89b-12d3-a456-426614174000"

UserId:
  name: user_id
  in: path
  required: true
  description: User UUID
  schema:
    type: string
    format: uuid
    example: "123e4567-e89b-12d3-a456-426614174000"

