ExperimentId:
  name: experiment_id
  in: path
  required: true
  schema:
    type: string
    format: uuid
RunId:
  name: run_id
  in: path
  required: true
  schema:
    type: string
    format: uuid
SessionId:
  name: session_id
  in: path
  required: true
  schema:
    type: string
    format: uuid
SensorId:
  name: sensor_id
  in: path
  required: true
  schema:
    type: string
    format: uuid
ProfileId:
  name: profile_id
  in: path
  required: true
  schema:
    type: string
    format: uuid
ArtifactId:
  name: artifact_id
  in: path
  required: true
  schema:
    type: string
    format: uuid
ProjectIdQuery:
  name: project_id
  in: query
  required: false
  schema:
    type: string
    format: uuid
  description: Override active project scope (requires owner/editor role).
IdempotencyKey:
  name: Idempotency-Key
  in: header
  required: false
  schema:
    type: string
  description: Provides idempotency on POST requests. When supplied, repeats must include the same body.
