"""Stub file for asyncpg."""
from typing import Any, Awaitable, AsyncContextManager, Protocol

class Connection(Protocol):
    def execute(self, query: str, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    def executemany(self, query: str, args: Any, *kwargs: Any) -> Awaitable[Any]: ...
    def fetch(self, query: str, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    def fetchval(self, query: str, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    def fetchrow(self, query: str, *args: Any, **kwargs: Any) -> Awaitable[Any]: ...
    def close(self) -> Awaitable[None]: ...
    def transaction(self) -> AsyncContextManager[Any]: ...
    async def __aenter__(self) -> "Connection": ...
    async def __aexit__(self, *args: Any) -> None: ...

class Pool(Protocol):
    def acquire(self) -> AsyncContextManager[Connection]: ...
    def close(self) -> Awaitable[None]: ...

class Record(Protocol):
    def __getitem__(self, key: Any) -> Any: ...
    def __contains__(self, key: Any) -> bool: ...
    def keys(self) -> Any: ...
    def values(self) -> Any: ...
    def items(self) -> Any: ...

def connect(*args: Any, **kwargs: Any) -> Awaitable[Connection]: ...

class exceptions:
    class InvalidCatalogNameError(Exception): ...
    class DuplicateObjectError(Exception): ...
    class DuplicateTableError(Exception): ...
